### ISSUE TITLE
npm not install in angular 12 !

### ISSUE THREAD

**Issue by mammadkoma** [aldrashan/angular-tui#3]
**npm install --save tui-image-editor-angular** not work.
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "tui-image-editor-angular" under a package
npm ERR! also called "tui-image-editor-angular". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\komaei\AppData\Roaming\npm-cache\_logs\2022-01-18T09_42_16_386Z-debug.log

**Comment by aldrashan** [comment]
Should also work with Angular 14 now.
